### PR TITLE
Fix HTML syntax.

### PR DESCRIPTION
**Pull request by marchof**

### CODE REVIEW

**Comment by marchof** [comment]
@Godin Strange, looks like the Travis build here runs on master. So previous PR (with broken HTML) was green, while this PR is red now.

**Comment by Godin** [comment]
@marchof this is really strange, because as far as I can see execution of generator is unconditional:

https://github.com/jacoco/www.eclemma.org/blob/e1390a87dea7d8a592dd6b491384045ba90721fa/.travis.sh#L37

only publishing depends on branch:

https://github.com/jacoco/www.eclemma.org/blob/e1390a87dea7d8a592dd6b491384045ba90721fa/.travis.sh#L62

**Comment by marchof** [comment]
That's what I'm saying: Even for PR we only checkout master of www.eclemma.org. That's why the typo in the HTML page was not detected.

Shouldn't this line

https://github.com/jacoco/www.eclemma.org/blob/e1390a87dea7d8a592dd6b491384045ba90721fa/.travis.sh#L18

read

    BRANCH1=${TRAVIS_BRANCH}

**Comment by Godin** [comment]
@marchof ah, you right 👍 actually script performs explicit checkout from master:

https://github.com/jacoco/www.eclemma.org/blob/e1390a87dea7d8a592dd6b491384045ba90721fa/.travis.sh#L18

which is result of copy-paste from script that previously was used manually - [updatesite.sh](https://github.com/jacoco/www.eclemma.org/blob/e1390a87dea7d8a592dd6b491384045ba90721fa/updatesite.sh)
Will need to change this.

And sorry for mistake 😞 on the other side good that it lead discovery of script weakness 😉

**Comment by Godin** [comment]
@marchof I hope to have time today (but a bit later) to more carefully check/think about

```diff
-BRANCH1=master
+BRANCH1=${TRAVIS_BRANCH}
```

maybe specification of branch can be removed altogether - this way same script will become usable locally.

**Comment by marchof** [comment]
@Godin Sure, as the script is now part of the repo anyways we can probably skip the checkout of www.jacoco.org repo (it should already be checked out by travis) and directly use its content.

If you want I can try to work on this.

**Pull request merged**
