### PR TITLE
Add link to recording of RockstarNight Dev Club 2019 presentation

### PR DESCRIPTION
**Pull request by Godin**

### CODE REVIEW

**Comment by marchof** [comment]
Do we really want to add a Facebook link to jacoco.org? 🙀

**Comment by Godin** [comment]
@marchof will you prefer a link to Twitter? 😆More seriously - what are the differences between a link to the event on Facebook and a link to any other site? 😉 I don't know other links that have a description of this particular event, so alternatively can only imagine removal of the link from the title or duplication of one of the two other links (site, video).

**Comment by marchof** [comment]
Ok, if you insist this will be the first link to Facebook from a site I maintain 🙈

**Comment by Godin** [comment]
Well, I wasn't insisting - just don't see it harms 😉

**Pull request merged**
