### PR TITLE
Add sha256 signatures

### PR DESCRIPTION
**Pull request by marchof**
Fixes jacoco/jacoco#982

I created the checksum files from my local copies with this script:

    for file in *.zip; do
      md5sum "$file" | awk '{ printf $1 }' > checksums/"$file".md5;
      sha256sum "$file" | awk '{ printf $1 }' > checksums/"$file".sha256;
    done

### CODE REVIEW

**Comment by marchof** [comment]
@Godin After this PR was pushed I realized that Github pages reports mime type `application/octet-stream` for the `*.md5` and `*.sha256` files. Which is not very user friendly to browser users who just want to e.g. copy the value.

I don't think this can be configured in Github pages. Therefore I propose to rename the siganture files to  `*.md5.txt` and `*.sha256.txt`. Ok?

**Comment by Godin** [comment]
@marchof sounds good! 👍

And since we speak about being user-friendly, I'd like to propose to also change the content of these files on a format that can be used with tools `md5sum` and `sha256sum`:

currently

```
# wget -q https://repo1.maven.org/maven2/org/jacoco/jacoco/0.8.5/jacoco-0.8.5.zip

# wget -q https://www.jacoco.org/jacoco/download/jacoco-0.8.5.zip.md5

# wget -q https://www.jacoco.org/jacoco/download/jacoco-0.8.5.zip.sha256

# md5sum -c jacoco-0.8.5.zip.md5
md5sum: jacoco-0.8.5.zip.md5: no properly formatted MD5 checksum lines found

# sha256sum -c jacoco-0.8.5.zip.sha256
sha256sum: jacoco-0.8.5.zip.sha256: no properly formatted SHA256 checksum lines found
```

whereas in the case of `jacoco-0.8.5.zip.md5.txt`

```
9c84437528104c68283ef9cc30b20d51  jacoco-0.8.5.zip
```

and `jacoco-0.8.5.zip.sha256.txt`

```
6f9dbfeb12238fd17ef1e99f0a83e2710681f99b27f9d76e9cb37e2b75f38b0a  jacoco-0.8.5.zip
```

we'll get

```
# md5sum -c jacoco-0.8.5.zip.md5.txt
jacoco-0.8.5.zip: OK

# sha256sum -c jacoco-0.8.5.zip.sha256.txt
jacoco-0.8.5.zip: OK
```

And sorry that I did not notice this before.

Do you want me to prepare both changes?

**Comment by marchof** [comment]
@Godin Good catch! Sure, if you find some time. Otherwise I can pick it up on friday.

**Comment by Godin** [comment]
@marchof here you go - https://github.com/jacoco/www.eclemma.org/pull/24

**Pull request merged**
